name: '"Setup Aliyun CLI" Action for GitHub Actions'
description: 'Setup Aliyun CLI action for GitHub Actions'

inputs:
  version:
    description: "The version of Aliyun CLI"
    required: false
    default: "latest"

runs:
  using: 'composite'
  steps:
    - id: setup
      shell: bash
      run: |
        VERSION=${{ inputs.version }}
        if [ "${{ runner.os }}" == "macOS" ]
        then
          curl https://aliyuncli.alicdn.com/aliyun-cli-macosx-$VERSION-universal.tgz -s | tar xvz -C /usr/bin/
        elif [ "${{ runner.os }}" == "Linux" && "${{ runner.arch }}" == "ARM64" ]
        then
          curl https://aliyuncli.alicdn.com/aliyun-cli-linux-$VERSION-arm64.tgz -s | tar xvz -C /usr/bin/
        elif [ "${{ runner.os }}" == "Linux" && "${{ runner.arch }}" == "X64" ]
        then
          curl https://aliyuncli.alicdn.com/aliyun-cli-linux-$VERSION-amd64.tgz -s | tar xvz -C /usr/bin/
        elif [ "${{ runner.os }}" == "Windows" ]
        then
          wget https://aliyuncli.alicdn.com/aliyun-cli-windows-$VERSION-amd64.zip
          Expand-Archive -Path ./aliyun-cli-windows-$VERSION-amd64.zip
          $env:PATH = $env:PATH";$pwd.Path"
        fi
        which aliyun
        aliyun version

branding:
  icon: 'cloud'
  color: 'orange'
